### ISSUE TITLE
Unknown type name 'Z3_bool_opt'

### ISSUE THREAD

**Issue by yangjunhuiyjh** [black-sat/homebrew-black#1]
I have followed the instruction for installing black on MacOS as outlined in https://github.com/black-sat/black/wiki/Installation#installation-on-macos. However, I got the following error message:

/tmp/black-sat-20220422-34925-p0a032/black-0.7.1/src/lib/src/sat/backends/z3.cpp:186:5: error: unknown type name 'Z3_bool_opt'
    Z3_bool_opt ok =
    ^
1 error generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/sat/backends/z3.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/lib/CMakeFiles/black.dir/all] Error 2
make: *** [all] Error 2

**Comment by nicola-gigante** [comment]
Hi, thanks for reporting. Maybe a new version of Z3 changed some details in the API. Let me check, I'll be back as soon as possible.

**Comment by nicola-gigante** [comment]
Hi! The new BLACK version 0.7.2 fixes the problem. You can retry installing BLACK using Homebrew. Please let me know if everything works for you as well.

**Comment by yangjunhuiyjh** [comment]
Thank you! I have downloaded successfully!
