### ISSUE TITLE
Problem installing via brew on Darwin Kernel Version 22.3.0 with arm64

### ISSUE THREAD

**Issue by 3brahimi** [black-sat/homebrew-black#2]
brew install black-sat/black/black-sat                                                                                  2 ↵  6110  18:06:56
==> Fetching black-sat/black/black-sat
==> Downloading https://github.com/black-sat/black/archive/v0.10.1.tar.gz
Already downloaded: /Users/ebrahimi/Library/Caches/Homebrew/downloads/cf3c18a5a630f2a148ce848461776a327b0584c0d135e2652b38a5f83a22f24e--black-0.10.1.tar.gz
==> Installing black-sat from black-sat/black
==> cmake . -DENABLE_MINISAT=NO
==> make
Last 15 lines from /Users/ebrahimi/Library/Logs/Homebrew/black-sat/02.make:
In file included from /tmp/black-sat-20230325-14013-1w5ue3r/black-0.10.1/src/lib/include/black/logic/logic.hpp:44:
In file included from /tmp/black-sat-20230325-14013-1w5ue3r/black-0.10.1/src/lib/include/black/internal/logic/core.hpp:29:
/tmp/black-sat-20230325-14013-1w5ue3r/black-0.10.1/src/lib/include/black/support/bitset.hpp:92:27: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
        if(b1._data[i] != b2._data[i])
                          ^~~~~~~~
/tmp/black-sat-20230325-14013-1w5ue3r/black-0.10.1/src/lib/include/black/support/bitset.hpp:99:15: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
      return (b1._data[_width - 1] & mask) == (b2._data[_width - 1] & mask);
              ^~~~~~~~
/tmp/black-sat-20230325-14013-1w5ue3r/black-0.10.1/src/lib/include/black/support/bitset.hpp:99:48: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
      return (b1._data[_width - 1] & mask) == (b2._data[_width - 1] & mask);
                                               ^~~~~~~~
10 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/logic/prettyprint.cpp.o] Error 1
make[1]: *** [src/lib/CMakeFiles/black.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/black-sat/homebrew-black/issues

**Comment by nicola-gigante** [comment]
Hi! Thanks for reporting! Homebrew upgraded to LLVM 16 some days ago and Clang 16 adds a new warning that triggers that error. I'll update the Homebrew formula as soon as possible. Stay tuned.

**Comment by 3brahimi** [comment]
Many thanks, I figured and tried to reproduce the error through source code installation just in case.

make                                                                                                                      ✔  6176  18:29:03
[  2%] Building CXX object src/lib/CMakeFiles/black.dir/src/logic/logic.cpp.o
In file included from /Users/ebrahimi/Workspace/FM/codes/black/src/lib/src/logic/logic.cpp:24:
In file included from /Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/logic/logic.hpp:44:
In file included from /Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:29:
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/support/bitset.hpp:77:7: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
      _data[word] = _data[word] | (uint64_t{1} << index);
      ^~~~~
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/support/bitset.hpp:51:9: note: in instantiation of member function 'black_internal::bitset::bitset<64>::set' requested here
        set(i);
        ^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:975:12: note: in instantiation of member function 'black_internal::bitset::bitset<64>::bitset' requested here
    return syntax_mask_t{static_cast<size_t>(child->type)};
           ^
In file included from /Users/ebrahimi/Workspace/FM/codes/black/src/lib/src/logic/logic.cpp:24:
In file included from /Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/logic/logic.hpp:44:
In file included from /Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:29:
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/support/bitset.hpp:77:21: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
      _data[word] = _data[word] | (uint64_t{1} << index);
                    ^~~~~
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/support/bitset.hpp:67:15: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
      return (_data[word] >> index) & 1;
              ^~~~~
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:354:21: note: in instantiation of function template specialization 'black_internal::bitset::bitset<64>::contains<black_internal::logic::syntax_element>' requested here
        Mask::value.contains(Element),
                    ^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:341:3: note: in instantiation of template class 'black_internal::logic::syntax_list_filter<black_internal::logic::syntax_list<black_internal::logic::syntax_element::relation, black_internal::logic::syntax_element::function, black_internal::logic::syntax_element::integer, black_internal::logic::syntax_element::real, black_internal::logic::syntax_element::constant, black_internal::logic::syntax_element::variable, black_internal::logic::syntax_element::application, black_internal::logic::syntax_element::negative, black_internal::logic::syntax_element::to_real, black_internal::logic::syntax_element::to_integer, black_internal::logic::syntax_element::next, black_internal::logic::syntax_element::wnext, black_internal::logic::syntax_element::prev, black_internal::logic::syntax_element::wprev, black_internal::logic::syntax_element::addition, black_internal::logic::syntax_element::subtraction, black_internal::logic::syntax_element::multiplication, black_internal::logic::syntax_element::division, black_internal::logic::syntax_element::int_division, black_internal::logic::syntax_element::boolean, black_internal::logic::syntax_element::proposition, black_internal::logic::syntax_element::atom, black_internal::logic::syntax_element::equal, black_internal::logic::syntax_element::distinct, black_internal::logic::syntax_element::less_than, black_internal::logic::syntax_element::less_than_equal, black_internal::logic::syntax_element::greater_than, black_internal::logic::syntax_element::greater_than_equal, black_internal::logic::syntax_element::exists, black_internal::logic::syntax_element::forall, black_internal::logic::syntax_element::negation, black_internal::logic::syntax_element::tomorrow, black_internal::logic::syntax_element::w_tomorrow, black_internal::logic::syntax_element::yesterday, black_internal::logic::syntax_element::w_yesterday, black_internal::logic::syntax_element::always, black_internal::logic::syntax_element::eventually, black_internal::logic::syntax_element::once, black_internal::logic::syntax_element::historically, black_internal::logic::syntax_element::conjunction, black_internal::logic::syntax_element::disjunction, black_internal::logic::syntax_element::implication, black_internal::logic::syntax_element::iff, black_internal::logic::syntax_element::until, black_internal::logic::syntax_element::release, black_internal::logic::syntax_element::w_until, black_internal::logic::syntax_element::s_release, black_internal::logic::syntax_element::since, black_internal::logic::syntax_element::triggered, black_internal::logic::syntax_element::named_sort, black_internal::logic::syntax_element::integer_sort, black_internal::logic::syntax_element::real_sort, black_internal::logic::syntax_element::var_decl, black_internal::logic::syntax_element::rel_decl, black_internal::logic::syntax_element::fun_decl, black_internal::logic::syntax_element::sort_decl>, black_internal::logic::hierarchy_syntax_mask<hierarchy_type::sort>>' requested here
  using syntax_list_filter_t =
  ^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:517:21: note: in instantiation of template type alias 'syntax_list_filter_t' requested here
    : make_fragment<syntax_list_filter_t<typename Syntax::list, Mask>> { };
                    ^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:520:3: note: in instantiation of template class 'black_internal::logic::fragment_filter<black_internal::logic::universal_fragment_t, black_internal::logic::hierarchy_syntax_mask<hierarchy_type::sort>>' requested here
  using fragment_filter_t = typename fragment_filter<Syntax, Mask>::type;
  ^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/core.hpp:1141:25: note: in instantiation of template type alias 'fragment_filter_t' requested here
    using node_syntax = fragment_filter_t<
                        ^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/hierarchy.hpp:438:1: note: in instantiation of template class 'black_internal::logic::hierarchy_base<black_internal::logic::hierarchy_type::sort, black_internal::logic::universal_fragment_t, black_internal::logic::sort>' requested here
declare_simple_hierarchy(sort)
^
/Users/ebrahimi/Workspace/FM/codes/black/src/lib/include/black/internal/logic/generation.hpp:380:11: note: expanded from macro 'declare_simple_hierarchy'
          hierarchy_base<hierarchy_type::Base, universal_fragment_t, Base>, \
          ^
3 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/logic/logic.cpp.o] Error 1
make[1]: *** [src/lib/CMakeFiles/black.dir/all] Error 2
make: *** [all] Error 2

**Comment by 3brahimi** [comment]
many thanks @nicola-gigante. I was wondering if we can request a feature and if so where?

**Comment by nicola-gigante** [comment]
Sure, please do it! :) you can open an issue at the main repository [here](https://github.com/black-sat/black).

**Comment by nicola-gigante** [comment]
@3brahimi a new `0.10.2` release is up, and should work without issues now. Let me know.

Best,
Nicola

**Comment by 3brahimi** [comment]
It is working through both `src` and `brew`.
